### PR TITLE
Remove black-magic from set method

### PR DESCRIPTION
**Pull request by kjirou**
I think that `IntermediateModel#set` is wrong architecture by the following reasons:
1. "emit events or not" should not be selectable from View side
   - Many subscribers exist in other than these views, at the normal situation
2. `silent` flag looks complicated (to me)
   - It is not a general architecture?

### CODE REVIEW

**Comment by khirayama** [comment]
I agree this changed.

> "emit events or not" should not be selectable from View side

I think so. But I have no idea to resolve this problem. Thanks.

> silent flag looks complicated (to me)

This answer is Yes. I felt that it is necessary. For example, we don't need emit event when render from server-side at first time.  
Use Backbone.js as reference. http://backbonejs.org/#Events-catalog

**Comment by kjirou** [comment]
Oh, Backbone was so..

> "emit events or not" should not be selectable from View side
> I think so. But I have no idea to resolve this problem. Thanks.

If you understand this point, I think that it is no problem!

---

In addition, in the case of myself, I would write this:

```
set: (key, value) ->
  @[key] = value

# it is callable from view side
updateData (data) ->
  @set('data') = data
  @emit('change_data')
```

I do not know it is correct or not!

**Comment by khirayama** [comment]
In this case, fetch method will be like this?

``` coffee
fetch: ->
 # pseudo ajax
 setTimeout( =>
  res = @genData()
  @updateData(res)
 , 300)
```

Or View should have fetch method?

**Comment by kjirou** [comment]
> In this case, fetch method will be like this?

Yes, can use it.

---

In this regard, I like this..

```
set: (key, value) ->
  @[key] = value

setAndEmit: (key, value) ->
  @set key, value
  # emit event
```

.. than this:

```
set: (key, value, silent) ->
  @[key] = value
  unless (silent)
    # emit event
```

**Comment by khirayama** [comment]
I see!
I'll accept this PR once and support set methods in this conversation. Thanks.

**Pull request merged**
