### PR TITLE
Fix unexpected closure

### PR DESCRIPTION
**Pull request by kjirou**
`_index` variable is bound by `TabView` class statically.
I think that it is not necessary if there is no special reason.

What do you think?

### CODE REVIEW

**Comment by kjirou** [comment]
supplement:

``` coffee
class Foo
  foo = 0

  constructor: ->
    @bar = 0

  increment: ->
    foo += 1
    @bar += 1

  getFoo: -> foo
  getBar: -> @bar

f1 = new Foo
f1.increment()
console.log f1.getFoo()  # -> 1
console.log f1.getBar()  # -> 1

f2 = new Foo
f2.increment()
console.log f2.getFoo()  # -> 2  .. unexpected?
console.log f2.getBar()  # -> 1
```

**Comment by khirayama** [comment]
That's right! Thanks for your advise and supplement!

**Comment by khirayama** [comment]
LGTM

**Comment by kjirou** [comment]
:+1:

**Pull request merged**
