### PR TITLE
Fix set method more simple.

### PR DESCRIPTION
**Pull request by khirayama**

### CODE REVIEW

**Comment by khirayama** [comment]
If possible, I want you review. @kjirou

**Comment by kjirou** [comment]
@khirayama Except for the part that is associated with #4, other part is LGTM!

**Comment by khirayama** [comment]
I understand and fix it!

**Comment by khirayama** [comment]
fix it!

**Comment by kjirou** [comment]
[LGTM](http://lgtm.in/i/gsMM1GQ8q)

**Comment by khirayama** [comment]
＼(^o^)／

**Pull request merged**
